### ISSUE TITLE
IFX007T-Motor-Control.h

### ISSUE THREAD

**Issue by Kla-Bel** [Infineon/IFX007T-Motor-Control#13]
Hello,
the library "IFX007T-Motor-Control.h" runs perfectly with the Arduino UNO.
Since I need more free pins I have to use the Arduino MEGA2560.
Is there already a library for this, or when is an update of the "IFX007T-Motor-Control.h" planned?
I only found one as of October 6, 2020. However, this is only for the UNO.
I would be very happy about a positive answer.

Best regards
Klaus

**Comment by BrixInMotion** [comment]
Hello Klaus,
I'm very sorry for the late response. But the good News is: there is already support for the Mega2560! Just select the "develop"-branch on the top left. Then manually download this library as zip, extract it and copy to your local Arduino/libraries/ folder. The only difference is the register-setting for the PWM-frequency.

Best Regards,
Kilian

**Comment by Kla-Bel** [comment]
Hello Kilian,
Thank you for your reference to the "IFX007T-Motor-Control.h" library.
I've loaded the library and will test it out when I get the chance.

Best Regards
Klaus
