### ISSUE TITLE
Incomplete PCB design data!

### ISSUE THREAD

**Issue by NavadeepGaneshU** [Infineon/IFX007T-Motor-Control#14]
Hi, 
Thanks for providing design files and all supporting libraries for IFX007T motor shield.

But, in the PCB Design Data, the .brd Eagle file is incomplete and layout is cluttered. I had a requirement for it to do some analysis and test and it would be helpful if it was fixed. Kindly look into this issue.

![Screenshot (1025)](https://user-images.githubusercontent.com/52508011/106610638-05617800-658d-11eb-86bc-3b614947e729.png)

**Comment by BrixInMotion** [comment]
Hi,
thank you for the comment.
Can you try the files I attached here? They should be fine.
BR
[PCB design Data.zip](https://github.com/Infineon/IFX007T-Motor-Control/files/5918883/PCB.design.Data.zip)

**Comment by NavadeepGaneshU** [comment]
Hi @BrixInMotion,
Thank you for quick response and resolution. Indeed, this design file is complete and prefect!
