### ISSUE TITLE
Keyboard Input not working.

### ISSUE THREAD

**Issue by allecsxxx** [Infineon/IFX007T-Motor-Control#15]
Uncommented
//======= Very important ========
#define DEBUG_IFX007T //Uncomment, if you wish debug output or tune the motor (Disables automatic V_neutralOffset)
//===============================

Used bldc pole find Sketch, all working, counts correctly ( i have 6 pole pairs)_**

Modified BEMF sketch for 6 pole pairs
bool direction = 1; // 0 or 1
uint8_t in;

//Create an instance of 'IFX007TMotorControl' called 'MyMotor'
IFX007TMotorControl MyMotor = IFX007TMotorControl();

void setup()
{
Serial.begin(115200);
Serial.println(" Infineon BLDC motor test! ");

MyMotor.begin();
// Adapt the following values according to the README if necessary
MyMotor.MotorParam.MotorPolepairs = 6; // Amount of polepairs. If your motor has 8 poles, it has 4 pole PAIRS)

Got this on Serial Monitor:
Infineon BLDC motor test!
Debug mode is active.
Sensorless BEMF mode
Started up sensorless BLDC motor.

Using t, g ,r,f,e,d keys ... nothing happens. Motor does 1 comutation stop, 1 comutation stop .... Any thoghts?

TY

**Comment by BrixInMotion** [comment]
Hi @allecsxxx,
are you sure that you're using the IFX007_BLDC_BEMF.ino sketch? 
If everything is wired correctly, it should at least increase speed for one second and afterwards go over in BEMF-block-commutation. Debug mode is only necessarry, if the motor stops again after the startup. 

Regards

**Comment by allecsxxx** [comment]
100% sure using bemf sketch.  everything is wired correctly ... i also burned 2 motors using the sketch... first of all i used Lipo battery about 40C ... motor went red in 1 second ! 2nd one i thought i will handle with a button in series with + to be able to disconnect battery quick enough... FAILED ... motor went smoke and dead. 

3rd motor i used a PSU that can handle 8 Amps ... motor goes hot but because psu goes in limitation mode when it reaches 8A motor is kind of protected .... but same ... rotor will align with the poles and will keep doing it for ever. 

First of all when i power up arduino (bldcshield already powered up at this point) motor will do maybe a full spin or more in less than 1 second than will stop and will keep try to start again and again and again ... at this point if I have the battery connected to power up the shield , motor will go red and smoke really bad ! Lucky with the 3rd motor i used a low amp power supply.


motor : https://hobbyking.com/en_us/d2830-11-1000kv-brushless-motor.html

Wired 3 cables in the black 3 way connector.
Shield is for BLDC as r25 26 27 are removed.


As i said above ... the only sketch that does not burn my motor is the sketch to find pole pairs. Although the motor goes quite hot! 



COPY -PASTE SKETCH FROM MY ARDUINO:


/**
 * This example code if for sensorless brushless motor application. The motor should be connected to the outputs U V and W.
 * Refer to the README.md in this folder.
 * 
*/

#include "IFX007T-Motor-Control.h"
uint8_t DutyCycle = 1;        //0-255   1 for keyboard input
bool direction = 0;           // 0 or 1

//Create an instance of 'IFX007TMotorControl' called 'MyMotor'
IFX007TMotorControl MyMotor = IFX007TMotorControl();

void setup()
{
  Serial.begin(115200);
  Serial.println(" Infineon BLDC motor test! ");

  MyMotor.begin();
  // Adapt the following values according to the README if necessary
  MyMotor.MotorParam.MotorPolepairs = 6;    // Amount of polepairs. If your motor has 8 poles, it has 4 pole PAIRS) 
  MyMotor.MotorParam.SensingMode = 0;       // If you use a Hallsensor set 1, for sensorless application 0
  
  MyMotor.MotorParam.V_neutral[0] = 160;    // High dutycycle, when V_neutral is const
  MyMotor.MotorParam.V_neutral[1] = 120;    // Value of high V_neutral
  MyMotor.MotorParam.V_neutral[2] = 50;     // Low dutycycle, when V_neutral is const 
  MyMotor.MotorParam.V_neutral[3] = 46;     // Value of low V_neutral
  MyMotor.MotorParam.Phasedelay[0] = 200;   // High dutycycle, when phasedelay is const
  MyMotor.MotorParam.Phasedelay[1] = 123;   // Value of high phasedelay
  MyMotor.MotorParam.Phasedelay[2] = 120;   // Low dutycycle, when phasedelay is const
  MyMotor.MotorParam.Phasedelay[3] = 80;    // Value of low phasedelay

  MyMotor.configureBLDCMotor(MyMotor.MotorParam);
}

void loop()
{
  MyMotor.setBLDCDutyCyclespeed(direction, DutyCycle);
  if (Serial.available() > 0)
  {
    uint8_t in = Serial.read();
    MyMotor.DebugRoutine(in);           //To set speed (and Parameters) via Keyboard input. See Documentation. 
  }
 
}




COPY -PASTE    "IFX007T-Motor-Control.h" :


#ifndef IFX007T_MOTOR_CONTROL_H
#define IFX007T_MOTOR_CONTROL_H

#include <Arduino.h>

//======= Very important ========
//#define DEBUG_IFX007T         //Uncomment, if you wish debug output or tune the motor (Disables automatic V_neutralOffset)
//===============================

#ifdef DEBUG_IFX007T
    #define DEBUG_PRINT_LN(str)  Serial.println(str)
    #define DEBUG_PRINT(str)  Serial.print(str)
    #define TRIGGER_PIN  digitalWrite(12, _debugPin); _debugPin = !_debugPin;
#else
	#define DEBUG_PRINT_LN(str)
    #define DEBUG_PRINT(str)
    #define TRIGGER_PIN
#endif

// --------------- Define row-names for the _PinAssignment - matrix -----------------------------------------------
#define INPUTPIN 0
#define INHIBITPIN 1
#define ADCPIN 2
#define REFVOLTAGE 3
// ----------------------------------------------------------------------------------------------------------------

#define TIMEOUT 500        // milliseconds

typedef struct
    {
        uint8_t MotorPolepairs;
        bool SensingMode;
        float PI_Reg_P;
        float PI_Reg_I;
        float V_neutral[4];
        float V_neutralFunct[2];        //Slope, offset
        float Phasedelay[4];
        float PhasedelayFunct[2];       //Slope, offset
    }BLDCParameter;

typedef struct
    {
        uint8_t in_U;
        uint8_t in_V;
        uint8_t in_W;
        uint8_t inh_U;
        uint8_t inh_V;
        uint8_t inh_W;
        uint8_t BEMF_U;
        uint8_t BEMF_V;
        uint8_t BEMF_W;
        uint8_t adc_Vneutral;
        uint8_t adc_IS;
        uint8_t adc_ISRC;
    }BLDCPinSetting;

//================ Class Definition ===============================================================================
class IFX007TMotorControl
{
    public:
    //------------- User Functions --------------------------------------------------------------------------------

                IFX007TMotorControl(void);
                IFX007TMotorControl(BLDCPinSetting MotorPins);
                ~IFX007TMotorControl(void);
        void    begin(void);
        void    end(void);

        void    setUniDirMotorSpeed(uint8_t motor, uint8_t dutycycle);                      //For Unidirectional motors
        void    setBiDirMotorSpeed(bool direction, uint8_t dutycycle);                      //For Bidirectional motors
        void    setBiDirMotorSpeed(bool direction, uint8_t dutycycle, uint8_t motor);       //For Bidirectional motors (overloaded function)
        
        void    configureBLDCMotor(BLDCParameter MyParameters);  
        void    setBLDCmotorRPMspeed(bool direction, uint16_t desired_rpmSpeed);
        void    setBLDCDutyCyclespeed(bool direction, uint8_t dutycycle);
        void    setHallBLDCmotorRPMspeed(bool direction, uint16_t desired_rpmSpeed, bool FieldWeakening);
        void    setHallBLDCmotorDCspeed(bool direction, uint8_t dutycycle, bool FieldWeakening); 
        uint8_t CommutateHallBLDC(uint8_t Dutycycle, bool hallsensor);                 
        void    DebugRoutine(uint8_t Serialinput);
        
    //------------- Variables ----------------------------------------------------
        uint8_t _Commutation = 0;
        BLDCParameter MotorParam;
        BLDCPinSetting MotorPins;

    private:
        bool    StartupBLDC(bool dir);                  // Algorithm to start up the motor, as long as theres no BEMF
        void    changeBEMFspeed(bool direction, uint16_t dutycycle);
        void    DoBEMFCommutation(bool dir);
        bool    DetectZeroCrossing(uint8_t Pin, bool sign);
        void    UpdateHardware(uint8_t CommutationStep);       //For BLDC motor
        void    calculateLinearFunction(float *array, float *result);
        void    setPwmFrequency(uint8_t pin, uint16_t divisor);
        void    PI_Regulator_DoWork(uint16_t desired_rpmSpeed);
        uint8_t UpdateHall(void);
        bool    WaitForCommutation(void);
        
        void    setADCspeedFast(void);

        /*  _________________________
            | INU   | INV   | INW   |
            | INHU  | INHV  | INHW  |
            | ADC_U | ADC_V | ADC_W |
            | ADC_VS| IS    | V_IS_RC
            |_______________________|
        */
        uint8_t _PinAssignment[4][3];
        uint8_t _BiDirMotorStatus=0;

        uint16_t _V_neutral;
        float _NumberofSteps;
        uint16_t _lastBLDCspeed;
        uint8_t _CurrentDutyCycle;
        bool _debugPin;
        uint16_t _Stepcounter = 0;
        uint32_t timerstart;
        uint32_t _TimeperRotation;

        // Values to start with, if debug option is turned on
        uint8_t iterations = 3;
        int16_t phasedelay = 90;
        uint8_t _V_NeutralOffset  = 100;

        // --------- For BLDC Hallsensor mode ----------

        /**
         * The first index switches between normal mode and fast mode (field weakening range)
         * The second index switches the direction between forward and backward
         * The third index for the pattern is the Hallsensor input as a dezimal value (e.g 0b00000101 is 5 dez)
         * The value at the index poition delivers the commutation state for the next step.
         */
        uint8_t HallPattern[2][2][7] = {
            {
                {9, 4,0,5,2,3,1},               /* Normal foreward */
                {9, 1,3,2,5,0,4}                /* Normal backward */
            },
            {
                {9, 5,1,0,3,4,2},               /* Fast foreward */
                {9, 0,2,1,4,5,3}                /* Fast backward */
            }
        };

        uint8_t _oldHall, _latestHall = 0;
        uint16_t _HallCounts = 0;
        unsigned long _PI_Update_Timeout = 999999999;
        float _PI_Integral = 0.0; 



};

#endif /**< IFX007_*/

**Comment by allecsxxx** [comment]
debug is commented now ( tried many ways to make it working) ...

**Comment by allecsxxx** [comment]
I also uploaded Sketch in Atmel studio , used debugger simulator and apparently the code flow never goes out of   

 void IFX007TMotorControl::UpdateHardware(uint8_t CommutationStep)

don t know what is going .... kind of don t understand all code so far ... to be able to trace it further i might need couple of days to fully understand it ... this is why i m asking here maybe i can get a bit of kickstart to atleast spin 1 motor without burning it :)

**Comment by allecsxxx** [comment]
Found the issue in the code . Since no one came to help I ll do the same! TY
