### ISSUE TITLE
Phase delay calculation

### ISSUE THREAD

**Issue by MarcP75006** [Infineon/IFX007T-Motor-Control#18]
Hello,
In the function "void IFX007TMotorControl::DoBEMFCommutation(bool direction)", shouldn't the line

` if(phasedelay > MotorParam.Phasedelay[1]) phasedelay = 120;`

rather be

` if(phasedelay > MotorParam.Phasedelay[1]) phasedelay = MotorParam.Phasedelay[1];`

so the phase delay would be set equal to the predefined value at high duty cycle ?

Best regards.

**Comment by BrixInMotion** [comment]
Hi @MarcP75006 

I guess you're right. The only thing I could imagine, that 120 was the value, where my motor did not turn at all anymore. But then it should be still configurable. I will trigger to check this.
Thanks for the hint!

Regards

**Comment by BrixInMotion** [comment]
The updated version is now available in the develop branch.
