### ISSUE TITLE
IFX007_BLDC_BEMF.ino

### ISSUE THREAD

**Issue by el-samiyel** [Infineon/IFX007T-Motor-Control#3]
Hi, great Lib.

One query: It is not clear whether this code is compatible with 32bit arduinos such as the Zero SAMD.

Will all of the timer code work?

Are you able to confirm this please.

Regards

**Comment by jaenrig-ifx** [comment]
Hi @el-samiyel ,

Do you mean the code in the master branch? 
We are refactoring this code into an Arduino library (check the develop branch). It will be released soon.
Currently the library is only compatible with the AVR core (Arduino Uno). But we are trying to make it compatible in general with any Arduino platform. We will check specifically for the Zero as well.

We will get back to you soon :)

**Comment by cemakkok** [comment]
Hi, i have tried to drive hoverboard motor with this sample code but i could not. I used 24V 2A power supply, actually that is enough power to drive it. I see first step but after that there is no movement. Do you have any guess ?

**Comment by BrixInMotion** [comment]
Hi @cemakkok ,

am I right in assuming that you want to use a (sensorless) brushless motor? And with hoverboard you mean these 2-wheel self-balancing scooters?

Unfortunately, this configuration will not work with this library, as it is intended to work for high speed BLDCs only and not for BLDC-applications where you need high torque with very low RPM. This would require Field-Oriented motor Control, which is not yet implemented.

Regards

**Comment by cemakkok** [comment]
Yes you are right @BrixInMotion but i have tried to drive only one wheel, i couldnt. Maybe i must try to implement FOC lib but is it possible with IFX007 ?

**Comment by BrixInMotion** [comment]
Depending on how much effort you want to spend on this project, you can of course try to implement FOC with this board. The IFX007t is basically only an intelligent halfbridge. So for FOC you would need e.g. an external current sensor / shunt (the current measurement with IFX007t is not precise enough for FOC) and a more powerfull microcontroller, like the XMC4700.

Another approach would be to use a [FOC-ready BLDC shield like this one](https://www.infineon.com/cms/en/product/evaluation-boards/bldc_shield_tle9879/).

**Comment by zjor** [comment]
Hello, I'm trying to compile examples and getting the following error:
```

libraries/IFX007T-Motor-Control/IFX007T-Motor-Control.cpp.o: In function `IFX007TMotorControl::begin()':
/Users/zjor/Documents/Arduino/libraries/IFX007T-Motor-Control/src/IFX007T-Motor-Control.cpp:92: undefined reference to `IFX007TMotorControl::setPwmFrequency(unsigned char, unsigned short)'
/Users/zjor/Documents/Arduino/libraries/IFX007T-Motor-Control/src/IFX007T-Motor-Control.cpp:93: undefined reference to `IFX007TMotorControl::setPwmFrequency(unsigned char, unsigned short)'
/Users/zjor/Documents/Arduino/libraries/IFX007T-Motor-Control/src/IFX007T-Motor-Control.cpp:94: undefined reference to `IFX007TMotorControl::setPwmFrequency(unsigned char, unsigned short)'
libraries/IFX007T-Motor-Control/IFX007T-Motor-Control.cpp.o: In function `IFX007TMotorControl::configureBLDCMotor(BLDCParameter)':
/Users/zjor/Documents/Arduino/libraries/IFX007T-Motor-Control/src/IFX007T-Motor-Control.cpp:291: undefined reference to `IFX007TMotorControl::setADCspeedFast()'
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board Arduino M0 Pro (Native USB Port).
```

The board is Arduino Zero SAMD

What am I missing here?

**Comment by BrixInMotion** [comment]
Hi zjor,

Arduino Zero SAMD is not supported by this library. You get this error, because there is not #ifdef for Arduino Zero. However you can add your own function setPWMFrequency(uint8_t , uint16_t) in `/src/IFX007T-Motor-Control.cpp` that changes the PWM Frequency to about 30kHz. The registeroperation for Arduino UNO won't work here. The function `setADCspeedFast()` you can uncomment completely I guess.

Regards
