### ISSUE TITLE
Using current sense to estimate the current torque on the motor

### ISSUE THREAD

**Issue by ddieffen** [Infineon/IFX007T-Motor-Control#4]
Thanks for developping this code and hardware.

It seems that the algorithm does not uses the current sense analog input. Would you be able to use it to estimate the torque applied to the motor ?

**Comment by BrixInMotion** [comment]
Hi @ddieffen ,
I already considered this option and I will give it a try to implement it, also I can not promise that it will work with sufficient accuracy.
Regards
