### ISSUE TITLE
formula for V_neutral

### ISSUE THREAD

**Issue by kgowthams** [Infineon/IFX007T-Motor-Control#8]
Hello,

Is the formula for v_neutral correct?
_V_neutral = (uint16_t) (analogRead(_PinAssignment[RefVoltage][0]) * (_CurrentDutyCycle/255.0)+0.5)-_V_NeutralOffset;

should it be *0.5 instead of +0.5, given that v_neutral is half of the reference voltage?

**Comment by BrixInMotion** [comment]
Hello,

no the formula is correct. The +0.5 is there to eliminate round-off errors. The scaling to half of Vcc is already done by a voltage divider on the shield. 

I hope this solved your issue.
Regards

**Comment by kgowthams** [comment]
Understood. Thank you for the clarification :)
